# ┌──────────────────────────────
# │ prd
# └──────────────────────────────
server:
  port.authorize: 9300
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:key/wildcard_ssookssook_io.pfx
    key-store-password: crudsystem1008!
    key-store-type: "PKCS12"

spring:
  profiles: prd
  datasource:
    url: jdbc:sqlserver://119.192.230.40:1433;DatabaseName=ssmsg2
    username: sa
    password: mincu1028!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDataSource
    max.pool.size: 100
    hikari:
      max-lifetime: 420000
      idle-timeout: 10000
      connection-timeout: 60000
      validation-timeout: 10000
      maximum-pool-size: 20
  redis:
    host: 211.233.87.134
    port: 4000
    password: crudsystem1008!
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  cache:
    type: redis
    redis:
      time-to-live: "60m"

resttemplate:
  max-connections: 3000
  connection.timeout: 30000
  #read.timeout: 20000
  read.timeout: 30000
  max.retry: 3
  try.count: 3

security:
  token.require: true


allow:
  ip.require: true

logging:
  db:
    api: false
    sql: false

api:
  url:
    ssmsg-message: https://authorize.ssookssook.io:9300

