# ┌──────────────────────────────
# │ loc
# └──────────────────────────────
server:
  port.eye: 9300
  http2:
    enabled: true
#  ssl:
#    enabled: false
#    key-store: classpath:key/wildcard_ssookssooki_io.pfx
#    key-store-password: crudsystem1008!
#    key-store-type: "PKCS12"

spring:
  profiles: loc
  datasource:
    url: jdbc:mariadb://211.233.81.190:33306/iwell
    username: root
    password: crudsystem1008!
    driver-class-name: org.mariadb.jdbc.MariaDbDataSource
    max.pool.size: 100
    hikari:
      max-lifetime: 420000
      idle-timeout: 10000
      connection-timeout: 60000
      validation-timeout: 10000
      maximum-pool-size: 20
  redis:
    host: 211.233.81.190
    port: 4000
    password: crudsystem1008!
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  cache:
    type: redis
    redis:
      time-to-live: "60m"

#  redis:
#    host: 49.247.27.148
#    port: 6379


resttemplate:
  max-connections: 3000
  connection.timeout: 30000
  #read.timeout: 20000
  read.timeout: 30000
  max.retry: 3
  try.count: 3

security:
  token.require: true

allow:
  ip.require: false

logging:
  db:
    api: true
    sql: true

api:
  url:
    eye: http://localhost:9300


