# ┌──────────────────────────────
# │ stg
# └──────────────────────────────
server:
  port.authorize: 9300
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:key/wildcard_ssookssook_io.pfx
    key-store-password: crudsystem1008!
    key-store-type: "PKCS12"

spring:
  profiles: stg
  datasource:
    url: jdbc:sqlserver://192.168.0.10:1433;DatabaseName=ssmsg2
    username: sa
    password: mincu1028!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDataSource
    max.pool.size: 100
    hikari:
      max-lifetime: 420000
      idle-timeout: 10000
      connection-timeout: 60000
      validation-timeout: 10000
      maximum-pool-size: 20
  redis:
    host: 211.233.81.190
    port: 4000
    password: crudsystem1008!
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  cache:
    type: redis
    redis:
      time-to-live: "60m"

#  redis:
#    host: 49.247.27.148
#    port: 6379


resttemplate:
  max-connections: 3000
  connection.timeout: 30000
  #read.timeout: 20000
  read.timeout: 30000
  max.retry: 3
  try.count: 3

security:
  token.require: true

allow:
  ip.require: false

logging:
  db:
    api: true
    sql: true

api:
  url:
    ssmsg-message: https://127.0.0.1:9300

